export const metadata = [
  { path: "game/ovo", title: "OvO | Slope Unblocked" },
  { path: "game/ovo-2", title: "OvO 2 | Slope Unblocked" },
  { path: "game/1v1-lol", title: "1v1.LOL | Slope Unblocked" },
  { path: "game/justfall-lol", title: "JustFall.LOL | Slope Unblocked" },
  { path: "game/cluster-rush", title: "Cluster Rush | Slope Unblocked" },
  { path: "game/bottle-flip-3d", title: "Bottle Flip 3D | Slope Unblocked" },
  { path: "game/2048", title: "2048 | Slope Unblocked" },
  { path: "game/stickman-hook", title: "Stickman Hook | Slope Unblocked" },
  { path: "game/drift-hunters", title: "Drift Hunters | Slope Unblocked" },
  { path: "game/basketball-stars", title: "Basketball Stars | Slope Unblocked" },
  { path: "game/run-3", title: "Run 3 | Slope Unblocked" },
  { path: "game/cookie-clicker", title: "Cookie Clicker | Slope Unblocked" },
  { path: "game/slope", title: "Slope | Slope Unblocked" },
  { path: "game/slope-3", title: "Slope 3 | Slope Unblocked" },
  {
    path: "game/worlds-hardest-game-3",
    title: "World's Hardest Game 3 | Slope Unblocked",
  },
  {
    path: "game/friday-night-funkin",
    title: "Friday Night Funkin' | Slope Unblocked",
  },
  { path: "game/mr-bullet", title: "Mr Bullet | Slope Unblocked" },
  { path: "game/among-us", title: "Among Us | Slope Unblocked" },
  { path: "game/moto-x3m", title: "Moto X3M | Slope Unblocked" },
  { path: "game/bitlife", title: "BitLife | Slope Unblocked" },
  { path: "game/color-switch", title: "Color Switch | Slope Unblocked" },
  { path: "game/google-snake", title: "Google Snake | Slope Unblocked" },
  { path: "game/color-road", title: "Color Road | Slope Unblocked" },
  { path: "game/flappy-bird", title: "Flappy Bird | Slope Unblocked" },
  { path: "game/paper-io-2", title: "Paper.io 2 | Slope Unblocked" },
  { path: "game/fnaf-2", title: "FNAF 2 | Slope Unblocked" },
  { path: "game/fnaf-3", title: "FNAF 3 | Slope Unblocked" },
  { path: "game/fnaf-4", title: "FNAF 4 | Slope Unblocked" },
  { path: "game/subway-surfers", title: "Subway Surfers | Slope Unblocked" },
  { path: "game/vex-6", title: "Vex 6 | Slope Unblocked" },
  { path: "game/funny-shooter-2", title: "Funny Shooter 2 | Slope Unblocked" },
  { path: "game/geometry-dash", title: "Geometery Dash | Slope Unblocked" },
  { path: "game/drive-mad", title: "Drive Mad | Slope Unblocked" },
  { path: "game/swingo", title: "Swingo | Slope Unblocked" },
  { path: "game/tag", title: "Tag | Slope Unblocked" },
  { path: "game/jetpack-joyride", title: "Jetpack Joyride | Slope Unblocked" },
  { path: "/", title: "Slope Unblocked" },
  { path: "games", title: "Slope Unblocked | Games" },
  { path: "socials", title: "Slope Unblocked | Socials" },
  { path: "*", title: "404" },
];
